/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlPanel;

import alertDialog.ConfirmMessageDialog;
import asconapplication.ASCONApplication;
import asconapplication.Constants;
import alertDialog.ErrorMessageDialog;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import listModel.ClientCellRenderer;
import listModel.ClientListModel;
import objectScripts.Client;
import objectScripts.SettingsVariable;

/**
 *
 * @author Oluwafemi Nehemiah (rotneil@yahoo.com)
 */
public final class ClientListPage extends javax.swing.JPanel implements Constants {

    // instance variables
    private final ASCONApplication asconApp;
    private SettingsVariable [] accomodation;
    private final ClientListModel clientListModel;
    private final ClientCellRenderer mRenderer;
    private ResultSet searchResult;
    private String nameSearch;
    private String addressSearch;
    private String companySearch;
    private String courseSearch;
    private String refNumber;
    private int accomodationSearch;
    private Client chosenClient;
    
    /**
     * Creates new form ClientPagePanel
     * @param ascon
     */
    public ClientListPage(ASCONApplication ascon) {
        this.asconApp = ascon;
        
        searchResult = ascon.getSchema().getAllClient();
        clientListModel = new ClientListModel (ascon, searchResult);
        mRenderer = new ClientCellRenderer (ascon);
        
        // form this array to have a zero-indexed element
        accomodation = ascon.getSchema().getSettings(SETTING.ACCOMODATION);
        SettingsVariable [] nAccom = new SettingsVariable [accomodation.length + 1];
        nAccom [0] = new SettingsVariable (0, "All");
        for (int i = 0; i < accomodation.length; ++i)
            nAccom [i + 1] = accomodation [i];
        accomodation = nAccom;
        
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientPopup = new javax.swing.JPopupMenu();
        viewItem = new javax.swing.JMenuItem();
        editItem = new javax.swing.JMenuItem();
        printItem = new javax.swing.JMenuItem();
        deleteItem = new javax.swing.JMenuItem();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        companyField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        refField = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();
        nameButton = new javax.swing.JButton();
        companyButton = new javax.swing.JButton();
        addressButton = new javax.swing.JButton();
        accomodationButton = new javax.swing.JButton();
        refButton = new javax.swing.JButton();
        accomodationCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        courseField = new javax.swing.JTextField();
        courseButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList();

        viewItem.setText("View Client Details");
        viewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemActionPerformed(evt);
            }
        });
        clientPopup.add(viewItem);

        editItem.setText("Edit Client Details");
        editItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editItemActionPerformed(evt);
            }
        });
        clientPopup.add(editItem);

        printItem.setText("Print Client Details");
        printItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printItemActionPerformed(evt);
            }
        });
        clientPopup.add(printItem);

        deleteItem.setText("Delete Client");
        deleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemActionPerformed(evt);
            }
        });
        clientPopup.add(deleteItem);

        setPreferredSize(new java.awt.Dimension(580, 526));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Client"));

        jLabel15.setText("Name of Client:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("Name of Company: ");

        companyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("Address: ");

        jLabel18.setText("Accomodation Type: ");

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        jLabel19.setText("Reference No: ");

        refField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refFieldActionPerformed(evt);
            }
        });

        resetButton.setText("Reset Search/List");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        nameButton.setText("Search");
        nameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameButtonActionPerformed(evt);
            }
        });

        companyButton.setText("Search");
        companyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyButtonActionPerformed(evt);
            }
        });

        addressButton.setText("Search");
        addressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressButtonActionPerformed(evt);
            }
        });

        accomodationButton.setText("Search");
        accomodationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accomodationButtonActionPerformed(evt);
            }
        });

        refButton.setText("Search");
        refButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refButtonActionPerformed(evt);
            }
        });

        accomodationCombo.setModel(new DefaultComboBoxModel <SettingsVariable>(accomodation));
        accomodationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accomodationComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Course Title: ");

        courseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseFieldActionPerformed(evt);
            }
        });

        courseButton.setText("Search");
        courseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(addressField)
                    .addComponent(companyField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refField)
                    .addComponent(accomodationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseField))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accomodationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameButton))
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(companyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyButton))
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressButton))
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(refField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refButton))
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseButton))
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(accomodationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accomodationButton))
                .addGap(3, 3, 3)
                .addComponent(resetButton))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Search List"));

        searchList.setModel(clientListModel);
        searchList.setCellRenderer(mRenderer);
        searchList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchListMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchListMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(searchList);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameButtonActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_nameButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_nameFieldActionPerformed

    private void companyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyFieldActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_companyFieldActionPerformed

    private void refFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refFieldActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_refFieldActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        resetSearch ();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchListMouseClicked
        // TODO add your handling code here:
        processClick (evt);
    }//GEN-LAST:event_searchListMouseClicked

    private void addressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressButtonActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_addressButtonActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_addressFieldActionPerformed

    private void accomodationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accomodationButtonActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_accomodationButtonActionPerformed

    private void refButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refButtonActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_refButtonActionPerformed

    private void accomodationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accomodationComboActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_accomodationComboActionPerformed

    private void companyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyButtonActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_companyButtonActionPerformed

    private void courseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseButtonActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_courseButtonActionPerformed

    private void courseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseFieldActionPerformed
        // TODO add your handling code here:
        refineSearch ();
    }//GEN-LAST:event_courseFieldActionPerformed

    private void viewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemActionPerformed
        // TODO add your handling code here:
        asconApp.showClientView(chosenClient.getClientLongAttribute(Client.ID));
    }//GEN-LAST:event_viewItemActionPerformed

    private void editItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editItemActionPerformed
        // TODO add your handling code here:
        asconApp.showClientEditPage(
                chosenClient, ACTION_CONTROLLER.CLIENT_PAGE);
    }//GEN-LAST:event_editItemActionPerformed

    private void printItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printItemActionPerformed
        // TODO add your handling code here:
        asconApp.showClientView(chosenClient.getClientLongAttribute(Client.ID));
    }//GEN-LAST:event_printItemActionPerformed

    private void deleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemActionPerformed
        // TODO add your handling code here:
        // prompt the user to confirm action
        boolean delete = ConfirmMessageDialog.show(asconApp, 
                "Are you sure you want to delete Clients details from the "
                        + "database?");
        if (delete) {
            asconApp.getSchema().deleteClient(
                    chosenClient.getClientLongAttribute(Client.ID));
            refineSearch();
        }
    }//GEN-LAST:event_deleteItemActionPerformed

    private void searchListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchListMouseReleased
        // TODO add your handling code here:
        try {
            if (evt.isPopupTrigger()) {
                // get the clicked index
                int index = searchList.locationToIndex(evt.getPoint());
                searchList.setSelectedIndex(index);
                searchResult.absolute(index + 1);
                chosenClient = asconApp.getSchema().getClientById(
                        searchResult.getLong(CLIENT.ID));
                clientPopup.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        } catch (java.sql.SQLException e) {}
    }//GEN-LAST:event_searchListMouseReleased

    
    // METHOD TO RESET THE SEARCH LIST
    private void resetSearch ()
    {
        nameField.setText("");
        companyField.setText("");
        addressField.setText("");
        refField.setText("");
        courseField.setText("");
        accomodationCombo.setSelectedIndex(0);
        
        searchResult = asconApp.getSchema().getAllClient();
        updateList ();
    }
    
    // METHOD TO REFINE SEARCH LIST
    private void refineSearch ()
    {
        // obtain user's input for all the fields
        try {
            nameSearch = nameField.getText();
            companySearch = companyField.getText();
            addressSearch = addressField.getText();
            courseSearch = courseField.getText();
            accomodationSearch = (int) ((SettingsVariable)accomodationCombo
                    .getSelectedItem()).getSettingsId ();
            refNumber = refField.getText();

            searchResult = asconApp.getSchema().getClient(nameSearch, 
                    companySearch, addressSearch, courseSearch, 
                    refNumber, accomodationSearch);
            updateList ();
        } catch (Exception e) {
            ErrorMessageDialog.show(asconApp, "SEARCH ERROR", e.getMessage());
        }
    }
    
    // METHOD TO RESPOND TO USER'S CLICKS
    private void processClick (java.awt.event.MouseEvent evt)
    {
        switch (evt.getClickCount()) {
            case 1: default:
                // DO NOTHING: ORDER BY NEHEMIAH
                break;
            case 2: // case for viewing client
                try {
                    int index = searchList.locationToIndex(evt.getPoint());
                    searchResult.absolute(index + 1);
                    chosenClient = asconApp.getSchema().getClientById(
                            searchResult.getLong(CLIENT.ID));
                    asconApp.showClientView(
                            chosenClient.getClientLongAttribute(Client.ID));
                } catch (SQLException e) {}
                break;
        }
    }
    
    // method to update list
    public void updateList ()
    {
        clientListModel.updateList(searchResult);
        searchList.setModel(clientListModel);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accomodationButton;
    private javax.swing.JComboBox accomodationCombo;
    private javax.swing.JButton addressButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JPopupMenu clientPopup;
    private javax.swing.JButton companyButton;
    private javax.swing.JTextField companyField;
    private javax.swing.JButton courseButton;
    private javax.swing.JTextField courseField;
    private javax.swing.JMenuItem deleteItem;
    private javax.swing.JMenuItem editItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nameButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JMenuItem printItem;
    private javax.swing.JButton refButton;
    private javax.swing.JTextField refField;
    private javax.swing.JButton resetButton;
    private javax.swing.JList searchList;
    private javax.swing.JMenuItem viewItem;
    // End of variables declaration//GEN-END:variables
}
