/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlPanel;

import asconapplication.ApplicationHomePage;
import asconapplication.Constants;
import asconapplication.SchemaHelper;
import javax.swing.DefaultComboBoxModel;
import objectScripts.Client;
import objectScripts.SettingsVariable;

/**
 *
 * @author Oluwafemi Nehemiah
 * rotenehe@gmail.com
 * 
 */
public class EditClientPage extends javax.swing.JPanel 
implements Constants{

    private final ApplicationHomePage parent;
    private final SchemaHelper mSchema;
    private Client mClient;
    
    private SettingsVariable [] accomodation;
    private SettingsVariable [] location;
    private SettingsVariable [] block;
    private SettingsVariable [] occupant;
    private SettingsVariable chosenAccomodation;
    private SettingsVariable chosenLocation;
    private SettingsVariable chosenBlock;
    private SettingsVariable chosenOccupant;
    private int status = STATUS.NOT_AVAILABLE;
    
    // variables used for the date 
    private String [] dayOfMonth;
    private String [] monthOfYear;
    private String [] year;
    private int chosenADayIndex, chosenAMonth, chosenAYear;
    private int chosenDDayIndex, chosenDMonth, chosenDYear;
    
    // flag to check if user has started entry
    private boolean FIELDS_CLEARED = false;
    
    /**
     * Creates new form RegisterPanel
     * @param parent
     */
    public EditClientPage(ApplicationHomePage parent, Client client) {
        this.parent = parent;
        this.mSchema = parent.getSchema();
        mClient = client;
        
        // date variables
        dayOfMonth = parent.getDaysOfMonth();
        monthOfYear = parent.getMonthOfYear();
        year = parent.getYear();
        
        // set the arrays to used by the combos
        accomodation = mSchema.getSettings(SETTING.ACCOMODATION);
        location = mSchema.getSettings(SETTING.LOCATION);
        block = mSchema.getSettings(SETTING.BLOCK_NAME);
        occupant = mSchema.getSettings(SETTING.OCCUPANT);
        initComponents();
        
        // set the default chosen items
        setDefaultValues ();
        
        // add buttons to status group button
        statusGroup.add(availableButton);
        statusGroup.add(notAvailableButton);
        
        // call method to initialize the value fields
        setAttributes ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusGroup = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        companyField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        blockCombo = new javax.swing.JComboBox();
        locationCombo = new javax.swing.JComboBox();
        occupantCombo = new javax.swing.JComboBox();
        arrivalMCombo = new javax.swing.JComboBox();
        departureMCombo = new javax.swing.JComboBox();
        accomodationCombo = new javax.swing.JComboBox();
        remarkField = new javax.swing.JTextField();
        arrivalDCombo = new javax.swing.JComboBox();
        arrivalYCombo = new javax.swing.JComboBox();
        departureDCombo = new javax.swing.JComboBox();
        availableButton = new javax.swing.JRadioButton();
        notAvailableButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        roomNumberField = new javax.swing.JTextField();
        departureYCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        courseField = new javax.swing.JTextField();
        departmentField = new javax.swing.JTextField();
        costField = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details"));

        jLabel6.setText("Name of Client: ");

        jLabel7.setText("Name of Company: ");

        jLabel8.setText("Address:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField)
                    .addComponent(companyField)
                    .addComponent(addressField)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(companyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resident Details"));

        jLabel10.setText("Block Name: ");

        jLabel11.setText("Location:");

        jLabel12.setText("Room No: ");

        jLabel13.setText("Occupants: ");

        jLabel1.setText("Arrival Date: ");

        jLabel3.setText("Departure: ");

        jLabel5.setText("Remark: ");

        blockCombo.setModel(new DefaultComboBoxModel(block));
        blockCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockComboActionPerformed(evt);
            }
        });

        locationCombo.setModel(new DefaultComboBoxModel(location));
        locationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboActionPerformed(evt);
            }
        });

        occupantCombo.setModel(new DefaultComboBoxModel(occupant));
        occupantCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupantComboActionPerformed(evt);
            }
        });

        arrivalMCombo.setModel(new DefaultComboBoxModel(monthOfYear));
        arrivalMCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalMComboActionPerformed(evt);
            }
        });

        departureMCombo.setModel(new DefaultComboBoxModel(monthOfYear));
        departureMCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureMComboActionPerformed(evt);
            }
        });

        accomodationCombo.setModel(new DefaultComboBoxModel(accomodation));
        accomodationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accomodationComboActionPerformed(evt);
            }
        });

        arrivalDCombo.setModel(new DefaultComboBoxModel(dayOfMonth));
        arrivalDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalDComboActionPerformed(evt);
            }
        });

        arrivalYCombo.setModel(new DefaultComboBoxModel(year));
        arrivalYCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalYComboActionPerformed(evt);
            }
        });

        departureDCombo.setModel(new DefaultComboBoxModel(dayOfMonth));
        departureDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureDComboActionPerformed(evt);
            }
        });

        availableButton.setText("Available");
        availableButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                availableButtonItemStateChanged(evt);
            }
        });

        notAvailableButton.setText("Not Available");
        notAvailableButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                notAvailableButtonItemStateChanged(evt);
            }
        });

        jLabel4.setText("Status:");

        departureYCombo.setModel(new DefaultComboBoxModel(year));
        departureYCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureYComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Accomodation: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(remarkField)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(arrivalDCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(departureDCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(departureMCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(arrivalMCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(blockCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(locationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(arrivalYCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(departureYCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 107, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(availableButton)
                                .addGap(28, 28, 28)
                                .addComponent(notAvailableButton))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(roomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(occupantCombo, 0, 141, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accomodationCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accomodationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(blockCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(locationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupantCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(arrivalMCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalYCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departureDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureMCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureYCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(notAvailableButton)
                    .addComponent(availableButton))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(remarkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cancelButton)
                .addComponent(saveButton))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Details"));

        jLabel14.setText("Course Title:");

        jLabel15.setText("Dept:");

        jLabel16.setText("Program Cost: ");

        costField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departmentField))
                    .addComponent(costField)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(courseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(departmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        // Primary use this method to set FIELDS CLEARED TO FALSE
        FIELDS_CLEARED = false;
    }//GEN-LAST:event_nameFieldActionPerformed

    private void blockComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockComboActionPerformed
        // TODO add your handling code here:
        chosenBlock = (SettingsVariable) blockCombo.getSelectedItem();
    }//GEN-LAST:event_blockComboActionPerformed

    private void locationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboActionPerformed
        // TODO add your handling code here:
        chosenLocation = (SettingsVariable) locationCombo.getSelectedItem();
    }//GEN-LAST:event_locationComboActionPerformed

    private void occupantComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupantComboActionPerformed
        // TODO add your handling code here:
        chosenOccupant = (SettingsVariable) occupantCombo.getSelectedItem();
    }//GEN-LAST:event_occupantComboActionPerformed

    private void arrivalMComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalMComboActionPerformed
        // TODO add your handling code here:
        chosenAMonth = arrivalMCombo.getSelectedIndex();
        chosenADayIndex = getDay(chosenAYear, chosenAMonth, chosenADayIndex);
        arrivalDCombo.setSelectedIndex(chosenADayIndex);

        FIELDS_CLEARED = false;
    }//GEN-LAST:event_arrivalMComboActionPerformed

    private void departureMComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureMComboActionPerformed
        // TODO add your handling code here:
        chosenDMonth = departureMCombo.getSelectedIndex();
        chosenDDayIndex = getDay(chosenDYear, chosenDMonth, chosenDDayIndex);
        departureDCombo.setSelectedIndex(chosenDDayIndex);
    }//GEN-LAST:event_departureMComboActionPerformed

    private void accomodationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accomodationComboActionPerformed
        // TODO add your handling code here:
        chosenAccomodation = (SettingsVariable) accomodationCombo.getSelectedItem();
        FIELDS_CLEARED = false;
    }//GEN-LAST:event_accomodationComboActionPerformed

    private void arrivalDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalDComboActionPerformed
        // TODO add your handling code here:
        chosenADayIndex = arrivalDCombo.getSelectedIndex();
        chosenADayIndex = getDay(chosenAYear, chosenAMonth, chosenADayIndex);
        arrivalDCombo.setSelectedIndex(chosenADayIndex);
    }//GEN-LAST:event_arrivalDComboActionPerformed

    private void arrivalYComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalYComboActionPerformed
        // TODO add your handling code here:
        chosenAYear = Integer.parseInt((String)arrivalYCombo.getSelectedItem());
        chosenADayIndex = getDay(chosenAYear, chosenAMonth, chosenADayIndex);
        arrivalDCombo.setSelectedIndex(chosenADayIndex);
    }//GEN-LAST:event_arrivalYComboActionPerformed

    private void departureDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureDComboActionPerformed
        // TODO add your handling code here:
        chosenDDayIndex = departureDCombo.getSelectedIndex();
        chosenDDayIndex = getDay(chosenDYear, chosenDMonth, chosenDDayIndex);
        departureDCombo.setSelectedIndex(chosenDDayIndex);
    }//GEN-LAST:event_departureDComboActionPerformed

    private void availableButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_availableButtonItemStateChanged
        // TODO add your handling code here:
        status = STATUS.AVAILABLE;
        FIELDS_CLEARED = false;
    }//GEN-LAST:event_availableButtonItemStateChanged

    private void notAvailableButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_notAvailableButtonItemStateChanged
        // TODO add your handling code here:
        status = STATUS.NOT_AVAILABLE;
        FIELDS_CLEARED = false;
    }//GEN-LAST:event_notAvailableButtonItemStateChanged

    private void departureYComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureYComboActionPerformed
        // TODO add your handling code here:
        chosenDYear = Integer.parseInt((String)departureYCombo.getSelectedItem());
        chosenDDayIndex = getDay(chosenDYear, chosenDMonth, chosenDDayIndex);
        departureDCombo.setSelectedIndex(chosenDDayIndex);
    }//GEN-LAST:event_departureYComboActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if (!FIELDS_CLEARED)
        clearFields ();
        else
        parent.changeActionPage(ACTION_CONTROLLER.HOME_PAGE);

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        processClientEdit ();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void costFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costFieldActionPerformed
        // TODO add your handling code here:
        processClientEdit ();
    }//GEN-LAST:event_costFieldActionPerformed

    // method to set the fields in the edit client page
    public void setAttributes ()
    {
        // uset the current Client to fill the fields
    }
    // method to process the edited client
    public void processClientEdit ()
    {
        // obtain new inputs and set to database
        
    }   // end processClientEdit

    /*
    ** This method clears the content of the Register panel for fresh entries
    ** Upon clearing, it updates the flag FIELDS_CLEARED
    */
    private void clearFields ()
    {
        // clear the fields
        nameField.setText("");
        companyField.setText("");
        addressField.setText("");
        roomNumberField.setText("");
        remarkField.setText("");
        courseField.setText("");
        costField.setText("");
        departmentField.setText("");
        accomodationCombo.setSelectedIndex(0);
        blockCombo.setSelectedIndex(0);
        locationCombo.setSelectedIndex(0);
        occupantCombo.setSelectedIndex(0);
        arrivalDCombo.setSelectedIndex(0);
        arrivalMCombo.setSelectedIndex(0);
        arrivalYCombo.setSelectedIndex(0);
        departureDCombo.setSelectedIndex(0);
        departureMCombo.setSelectedIndex(0);
        departureYCombo.setSelectedIndex(0);
        notAvailableButton.setSelected(true);
        
        // set the instance variables to default
        setDefaultValues ();
        
        // toggle clearFields
        FIELDS_CLEARED = true;
    }
    
    /*
    ** Method to returnt the ComboBoxes to their default values
    */
    private void setDefaultValues ()
    {
        chosenAccomodation = (SettingsVariable) accomodationCombo
                .getSelectedItem();
        chosenLocation = (SettingsVariable) locationCombo.getSelectedItem();
        chosenBlock = (SettingsVariable) blockCombo.getSelectedItem();
        chosenOccupant = (SettingsVariable) occupantCombo.getSelectedItem();
        
        // set the default chosen date items
        chosenADayIndex = arrivalDCombo.getSelectedIndex();
        chosenAMonth = arrivalMCombo.getSelectedIndex();
        chosenAYear = Integer.parseInt((String)arrivalYCombo.getSelectedItem());
        chosenDDayIndex = departureDCombo.getSelectedIndex();
        chosenDMonth = departureMCombo.getSelectedIndex();
        chosenDYear = Integer.parseInt((String)departureYCombo.getSelectedItem());
        
    }
    
    // method to set an appropriate month day
    private int getDay (int year, int month, int day) {
        switch (month) {
            case 1: // FEBRUARY
                if (day > 27) {
                    if (year % 4 == 0)
                        return 28;
                    else
                        return 27;
                } else
                    return day;
            case 3: // APRIL
            case 5: // JUNE
            case 8: // SEPTEMBER
            case 10: // NOVEMBER
                if (day > 29)
                    return 29;
                else
                    return day;
            default:
                return day;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accomodationCombo;
    private javax.swing.JTextField addressField;
    private javax.swing.JComboBox arrivalDCombo;
    private javax.swing.JComboBox arrivalMCombo;
    private javax.swing.JComboBox arrivalYCombo;
    private javax.swing.JRadioButton availableButton;
    private javax.swing.JComboBox blockCombo;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField companyField;
    private javax.swing.JTextField costField;
    private javax.swing.JTextField courseField;
    private javax.swing.JTextField departmentField;
    private javax.swing.JComboBox departureDCombo;
    private javax.swing.JComboBox departureMCombo;
    private javax.swing.JComboBox departureYCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox locationCombo;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton notAvailableButton;
    private javax.swing.JComboBox occupantCombo;
    private javax.swing.JTextField remarkField;
    private javax.swing.JTextField roomNumberField;
    private javax.swing.JButton saveButton;
    private javax.swing.ButtonGroup statusGroup;
    // End of variables declaration//GEN-END:variables
}
