/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listModel;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import objectScripts.ASCONEvent;

/**
 *
 * @author Adesola
 */
public class EventListRenderer extends javax.swing.JPanel 
    implements ListCellRenderer<ASCONEvent> {

    /**
     * Creates new form EventListRenderer
     */
    public EventListRenderer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        messageArea.setBackground(new java.awt.Color(240, 240, 240));
        messageArea.setColumns(20);
        messageArea.setLineWrap(true);
        messageArea.setRows(5);
        messageArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(messageArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(
            JList<? extends ASCONEvent> list, ASCONEvent value, int index, 
            boolean isSelected, boolean cellHasFocus) {
        messageArea.setText(new SimpleDateFormat ("dd MMM, YYYY").format (
                value.getDate()));
        messageArea.append("\n" + value.getShortMesage());
        Color background;
        Color foreground;
        
        // check if the cell is selected or not
        if (isSelected) {
            background = Color.cyan;
            foreground = Color.white;
        } else {
            background = Color.white;
            foreground = Color.black;
        }
        
        setBackground (background);
        setForeground (foreground);
        return this;
    }
}
